name: Deployment

on:
  push:
    branches:
      - main
      - dev

env:
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.rlfb0i4.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Start server and wait
        run: npm start & npx wait-on http://127.0.0.1:$PORT --timeout 60000

      - name: Run tests
        run: npm test

      - name: Show environment variables
        run: echo "Running tests with DB: ${{ env.MONGODB_DB_NAME }} and user: ${{ env.MONGODB_USERNAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      MONGODB_DB_NAME: gha-demo
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy output info
        run: |
          echo "Deploying with DB: ${{ env.MONGODB_DB_NAME }}"
          echo "Deploy user: ${{ env.MONGODB_USERNAME }}"
